[config]
default_to_workspace = false

# Metatasks invoked by CI
# Tests

[tasks.test-java-feature.mac]
env = {"OUT_FILE" = "dylib"}

[tasks.test-java-feature.linux]
env = {"OUT_FILE" = "so", "LD_LIBRARY_PATH" = "./"}

[tasks.test-java-feature]
category = "Tests"
script_runner = "@bash"
dependencies = ["build-feature"]
script = '''
cargo build --release -p feature-tests
cp target/debug/libfeature_test.{OUTFILE} feature/java/somelib/libsomelib.{OUTFILE}
cd feature/java/somelib
mvn test
'''


[tasks.gen-java-feature]
category = "Code generation"
script_runner = "@bash"
script = '''
mkdir feature/tmp
cargo run -p diplomat-java -- -e feature/src/lib.rs -l feature/diplomat-java-conf.toml feature/tmp/
rm -r feature/java/somelib/src/main
mv feature/tmp/src/main feature/java/somelib/src/main
rm -r feature/tmp
'''
# Build deps

[tasks.build-feature]
description = "Build feature_tests"
category = "Plumbing"
command = "cargo"
args = ["build", "-p", "feature-tests"]

[tasks.bench-rust-feature]
description = "Benchmark rust example"
category = "Benchmark"
script = '''
cargo bench --package diplomat-example
'''
[tasks.bench-java-feature]
description = "Benchmark kotlin example"
category = "Benchmark"
dependencies = ["gen-kotlin-example", "test-kotlin-example"]
script = '''
cd example/kotlin/somelib
gradle jmh --warning-mode all
'''
