
name: Check Diplomat

on:
  schedule:
    - cron: "0 0 * * 5"
      branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-latest-diplomat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check rustfmt
      run: cargo add -p diplomat-java --git https://github.com/rust-diplomat/diplomat.git diplomat-tool diplomat-runtime diplomat_core diplomat

    - name: Check clippy
      run: cargo build
