
name: Check Diplomat Compatibility

on:
  schedule:
    - cron: "56 0 * * 5"
      branches: [ move-panama-backend ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-latest-diplomat:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add latest dipomat
      run: cargo add -p diplomat-java --git https://github.com/rust-diplomat/diplomat.git --branch main diplomat-tool diplomat-runtime diplomat_core

    - name: Check build
      run: cargo build
