name: Diplomat Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check rustfmt
      run: cargo fmt --all -- --check

    - name: Check clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

  msrv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install MSRV Rust
      run: rustup install 1.71 --profile minimal

    - name: Check
      run: cargo +1.71 check -p diplomat-java -p jextrsact -p feature-tests

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-make
      uses: taiki-e/install-action@cargo-make
    - name: Set up JDK 22 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: Test Java
      run: cargo make test-feature

  test-gen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-make
      uses: taiki-e/install-action@cargo-make
    - name: Install curl
      run: sudo apt-get update && sudo apt-get install -y curl
    - name: Set up JDK 22 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        architecture: x64
        cache: maven
    - name: get jextract
      run: curl -o /opt/jextract.tgz https://download.java.net/java/early_access/jextract/22/5/openjdk-22-jextract+5-33_linux-x64_bin.tar.gz
    - name: config jextract
      run: tar -xzf /opt/jextract.tgz -C /opt/
    - name: Add jextract to path
      run: echo "/opt/jextract-22/bin" >> $GITHUB_PATH
    - name: Run generated java
      run: cargo make gen-feature

